services:
  frontend:
    ports:
      - "80:3000"

  emqx:
    ports:
      - "1883:1883" # TCP
      - "8083:8083" # WS
      - "8084:8084" # WSS
      - "8883:8883" # TLS
      - "18083:18083" # Dashboard