// Code generated by BobGen psql v0.38.0. DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package factory

import "context"

type Factory struct {
	baseIotAlertEventMods   IotAlertEventModSlice
	baseSchemaMigrationMods SchemaMigrationModSlice
}

func New() *Factory {
	return &Factory{}
}

func (f *Factory) NewIotAlertEvent(ctx context.Context, mods ...IotAlertEventMod) *IotAlertEventTemplate {
	o := &IotAlertEventTemplate{f: f}

	if f != nil {
		f.baseIotAlertEventMods.Apply(ctx, o)
	}

	IotAlertEventModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) NewSchemaMigration(ctx context.Context, mods ...SchemaMigrationMod) *SchemaMigrationTemplate {
	o := &SchemaMigrationTemplate{f: f}

	if f != nil {
		f.baseSchemaMigrationMods.Apply(ctx, o)
	}

	SchemaMigrationModSlice(mods).Apply(ctx, o)

	return o
}

func (f *Factory) ClearBaseIotAlertEventMods() {
	f.baseIotAlertEventMods = nil
}

func (f *Factory) AddBaseIotAlertEventMod(mods ...IotAlertEventMod) {
	f.baseIotAlertEventMods = append(f.baseIotAlertEventMods, mods...)
}

func (f *Factory) ClearBaseSchemaMigrationMods() {
	f.baseSchemaMigrationMods = nil
}

func (f *Factory) AddBaseSchemaMigrationMod(mods ...SchemaMigrationMod) {
	f.baseSchemaMigrationMods = append(f.baseSchemaMigrationMods, mods...)
}
